LeaderboardBackend.Test/Controllers/LeaderboardsControllerTest.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Controllers/Requests/Leaderboards/Create.cs
LeaderboardBackend/Models/Leaderboard.cs
LeaderboardBackend/Models/LeaderboardContext.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/Services/ILeaderboardService.cs
LeaderboardBackend/Services/LeaderboardService.cs

This adds `Leaderboard`. Quite a few things left to do, as listed below, which speaking of, I'd like to ask which items should be included in this PR, and which ones should be left for another.
- Leaderboard model, context, and controller
- Service registration in `Program.cs`
- Creation of and finding leaderboards (single and multiple IDs)
- Put and delete requests (creation request done)
- Authentication + authorisation (e.g. how only admins should be able to create a leaderboard)
- Relationship definitions with other models

Add Leaderboard Model

---

LeaderboardBackend/Program.cs

I think this just got clobbered in a rebase by accident

Re-add claim name remap clearing

---

LeaderboardBackend/Program.cs

Closes #17 
Add a json serialization option to camelcase all incoming and outgoing json serialized and deserialized by the controllers.

Add Json Serialization Option

---

LeaderboardBackend.Test/Controllers/UsersControllerTests.cs
LeaderboardBackend.Test/Services/AuthServiceTests.cs
LeaderboardBackend/Controllers/UsersController.cs
LeaderboardBackend/Models/User.cs
LeaderboardBackend/Services/IUserService.cs
LeaderboardBackend/Services/UserService.cs

[REVIEW FIRST]: MVP: Swap User IDs from Numeric to GUID

---

LeaderboardBackend.Integration/LeaderboardBackend.Integration.csproj
LeaderboardBackend.Integration/TestApiFactory.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/appsettings.Staging.json
LeaderboardBackend/appsettings.json
docker-compose.yml
example.env
leaderboard-backend-poc.sln

Working towards closing #6 
* Add IntegrationTest project
* Include .env in build for integration test project
* Use `Program.cs` as WebApplicationFactory entry point
* Use `Staging` environment for integration tests
* db_test now mounts the correct port on the container
* Adjust env var for test port (test DB will now share name)
* Created TestApiFactory, a base class for future integration tests that will set Staging environment and clear database each tests

Add Integration Test setup

---

.gitignore
.vscode/extensions.json
.vscode/tasks.json
LeaderboardBackend.Test/Models/Requests/RegisterTests.cs
LeaderboardBackend/Controllers/Requests/Login.cs
LeaderboardBackend/Controllers/Requests/PasswordAttribute.cs
LeaderboardBackend/Controllers/Requests/Register.cs
LeaderboardBackend/Controllers/UsersController.cs
LeaderboardBackend/Models/User.cs
LeaderboardBackend/Services/IUserService.cs
LeaderboardBackend/Services/UserService.cs

Closes: #20.
This should serve as a foundation for other model validations.

MVP: User Model Validation

---

.github/workflows/test-backend.yml

Fix yaml syntax

---

LeaderboardBackend/Controllers/BansController.cs
LeaderboardBackend/Controllers/ParticipationController.cs
LeaderboardBackend/Migrations/20220422133712_CreateParticipations.Designer.cs
LeaderboardBackend/Migrations/20220422133712_CreateParticipations.cs
LeaderboardBackend/Models/Entities/ApplicationContext.cs
LeaderboardBackend/Models/Entities/Participation.cs
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/Entities/User.cs
LeaderboardBackend/Models/Requests/Participations/Create.cs
LeaderboardBackend/Models/Requests/Participations/Update.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/Services/IBanService.cs
LeaderboardBackend/Services/IParticipationService.cs
LeaderboardBackend/Services/Impl/BanService.cs
LeaderboardBackend/Services/Impl/ParticipationService.cs
LeaderboardBackend/Services/Impl/RunService.cs

Copied the important code from #49 and #53 into the new project structure.
I am skipping the tests in this PR because the next PR I'm merging has new helpers that we're going to conform all tests to.

Added Partipations, BanController

---

LeaderboardBackend/Controllers/BansController.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Controllers/UsersController.cs
README.md

Issue 81: https://github.com/leaderboardsgg/leaderboard-backend/issues/81
Removed/replaced any ProduceResponseType attributes in BansController.cs and RunsController.cs with ApiConventionMethod attributes.
added a comment to the readme for something that tripped me up during setup.
added some more detail to a comment pointing to an example of CompareAttribute in the UsersController.

Issue81 controller attributes

---

LeaderboardBackend.Test/Judgements.cs
LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Controllers/BansController.cs
LeaderboardBackend/Migrations/20220627030602_Bans_TimestampChanges.cs
LeaderboardBackend/Migrations/20220726155057_DateTimeToInstant.Designer.cs
LeaderboardBackend/Migrations/20220726155057_DateTimeToInstant.cs
LeaderboardBackend/Models/Entities/Judgement.cs
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/Requests/RunRequests.cs
LeaderboardBackend/Models/ViewModels/JudgementViewModel.cs

Swap DateTimes to NodaTime.Instants

---

LeaderboardBackend/Controllers/BansController.cs
LeaderboardBackend/Controllers/CategoriesController.cs
LeaderboardBackend/Controllers/JudgementsController.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Controllers/ModshipsController.cs
LeaderboardBackend/Controllers/ParticipationsController.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Controllers/UsersController.cs
LeaderboardBackend/Models/Entities/Ban.cs
LeaderboardBackend/Models/Entities/Category.cs
LeaderboardBackend/Models/Entities/Judgement.cs
LeaderboardBackend/Models/Entities/Leaderboard.cs
LeaderboardBackend/Models/Entities/Modship.cs
LeaderboardBackend/Models/Entities/Participation.cs
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/Entities/User.cs
LeaderboardBackend/Models/Requests/BanRequests.cs
LeaderboardBackend/Models/Requests/CategoryRequests.cs
LeaderboardBackend/Models/Requests/JudgementRequests.cs
LeaderboardBackend/Models/Requests/LeaderboardRequests.cs
LeaderboardBackend/Models/Requests/ModshipRequests.cs
LeaderboardBackend/Models/Requests/ParticipationRequests.cs
LeaderboardBackend/Models/Requests/RunRequests.cs
LeaderboardBackend/Models/Requests/UserRequests.cs
LeaderboardBackend/Models/ViewModels/JudgementViewModel.cs

Extends #121 and thereby closes #117.

Improve documentation comments (#117)

---

LeaderboardBackend.Test/Bans.cs
LeaderboardBackend.Test/Categories.cs
LeaderboardBackend.Test/Judgements.cs
LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend.Test/Modships.cs
LeaderboardBackend.Test/Runs.cs
LeaderboardBackend.Test/Users.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Migrations/20221011195842_Runs_AddCategory.Designer.cs
LeaderboardBackend/Migrations/20221011195842_Runs_AddCategory.cs
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/Requests/RunRequests.cs
LeaderboardBackend/Services/ICategoryService.cs
LeaderboardBackend/Services/Impl/CategoryService.cs

- Added CategoryId to Run model
- Added GetCategory for RunController
- adapted tests
- Edited CreateRun to enter a CategoryId

Added Category for Runs

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend.Test/TestApi/Extensions/UserApiExtensions.cs
LeaderboardBackend.Test/Users.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Controllers/UsersController.cs
LeaderboardBackend/Migrations/20230603155624_Runs_RemoveRunStatus.Designer.cs
LeaderboardBackend/Migrations/20230603155624_Runs_RemoveRunStatus.cs
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/Requests/RunRequests.cs
LeaderboardBackend/Models/ViewModels/RunViewModel.cs
LeaderboardBackend/Models/ViewModels/UserViewModel.cs
LeaderboardBackend/openapi.json

Based on PR https://github.com/leaderboardsgg/leaderboard-backend/pull/145
I left out some fields because we have no spec requiring them for now:
- User viewmodel
- `About`
- `Admin`
- Run viewmodel:
- `PlayedOn`
- `Status`
Closes #131

Add run and user view models

---

LeaderboardBackend.Test/Features/Emails/EmailSenderTests.cs
LeaderboardBackend.Test/LeaderboardBackend.Test.csproj
LeaderboardBackend.Test/TestApi/TestApiFactory.cs
LeaderboardBackend/LeaderboardBackend.csproj
LeaderboardBackend/Program.cs
LeaderboardBackend/Services/IEmailSender.cs
LeaderboardBackend/Services/Impl/EmailSender.cs
LeaderboardBackend/Services/Impl/EmailSenderConfig.cs
LeaderboardBackend/appsettings.json
example.env

Add EmailSender

---

.editorconfig
LeaderboardBackend.Test/Categories.cs
LeaderboardBackend.Test/Features/Users/LoginTests.cs
LeaderboardBackend.Test/Features/Users/RegistrationTests.cs
LeaderboardBackend.Test/Fixtures/IntegrationTestsBase.cs
LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Authorization/Jwt.cs

Don't enforce Hungarian notation for statics.

---

LeaderboardBackend/Migrations/20230806090228_AddAccountRecovery.Designer.cs
LeaderboardBackend/Migrations/20230806090228_AddAccountRecovery.cs
LeaderboardBackend/Models/Entities/AccountRecovery.cs
LeaderboardBackend/Models/Entities/ApplicationContext.cs
LeaderboardBackend/Models/Entities/User.cs

Add Account Recovery Model

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Binders/UrlSafeBase64GuidBinder.cs
LeaderboardBackend/Extensions/GuidExtensions.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/openapi.json

This PR makes GUIDs parsed from path elements use a more compact format. Closes #186

Standardize GUID format

---

LeaderboardBackend/Controllers/AccountController.cs

This PR is just to cleanup a few leftover pragmas/unused params in the account controller.

Resend confirmation cleanup

---

LeaderboardBackend.Test/Consts.cs
LeaderboardBackend.Test/Features/Users/AccountRecoveryTests.cs
LeaderboardBackend/Controllers/AccountController.cs
LeaderboardBackend/Controllers/ApiController.cs
LeaderboardBackend/Models/Entities/AccountRecovery.cs
LeaderboardBackend/Models/Requests/UserRequests.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/Results.cs
LeaderboardBackend/Services/IAccountConfirmationService.cs
LeaderboardBackend/Services/IAccountRecoveryService.cs
LeaderboardBackend/Services/IUserService.cs
LeaderboardBackend/Services/Impl/AccountConfirmationService.cs
LeaderboardBackend/Services/Impl/AccountRecoveryService.cs
LeaderboardBackend/Services/Impl/UserService.cs
LeaderboardBackend/openapi.json

Account Recovery Endpoint

---

LeaderboardBackend.Test/Features/Users/ResetPasswordTests.cs
LeaderboardBackend/Controllers/AccountController.cs
LeaderboardBackend/Models/Requests/UserRequests.cs
LeaderboardBackend/Services/IAccountRecoveryService.cs
LeaderboardBackend/Services/Impl/AccountRecoveryService.cs
LeaderboardBackend/openapi.json

Password Reset Endpoint

---

LeaderboardBackend.Test/Features/Users/RegistrationTests.cs
LeaderboardBackend.Test/Features/Users/SendConfirmationTests.cs
LeaderboardBackend/Controllers/AccountController.cs
LeaderboardBackend/Services/Impl/AccountConfirmationService.cs
LeaderboardBackend/Services/Impl/UserService.cs
LeaderboardBackend/openapi.json

Send Confirmation Email on Register

---

LeaderboardBackend/Controllers/AccountController.cs
LeaderboardBackend/Extensions/StringExtensions.cs
LeaderboardBackend/Services/Impl/AccountRecoveryService.cs

Adds:
* A little bit of logs to `AccountController` and `AccountRecoveryService`

Add Debug Logs on Account Recovery

---

LeaderboardBackend.Test/Features/Users/RegistrationTests.cs
LeaderboardBackend/Models/ViewModels/UserViewModel.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/openapi.json

This PR adds a Role field to UserViewModel so that frontend can determine the role of any given user.

Add Role to UserViewModel

---

.config/dotnet-tools.json
LeaderboardBackend.Test/Features/Users/RegistrationTests.cs
LeaderboardBackend/LeaderboardBackend.csproj
LeaderboardBackend/Migrations/20240830045334_AddMissingConstraints.Designer.cs
LeaderboardBackend/Migrations/20240830045334_AddMissingConstraints.cs
LeaderboardBackend/Migrations/20240830174734_SwitchToCitext.Designer.cs
LeaderboardBackend/Migrations/20240830174734_SwitchToCitext.cs
LeaderboardBackend/Migrations/20240830175418_RemoveCaseInsensitiveCollation.Designer.cs
LeaderboardBackend/Migrations/20240830175418_RemoveCaseInsensitiveCollation.cs
LeaderboardBackend/Migrations/20240830180443_UserAddEmailRegex.Designer.cs
LeaderboardBackend/Migrations/20240830180443_UserAddEmailRegex.cs
LeaderboardBackend/Migrations/20240830181543_UserAddUsernameRegex.Designer.cs
LeaderboardBackend/Migrations/20240830181543_UserAddUsernameRegex.cs
LeaderboardBackend/Migrations/20240831195900_LeaderboardsExcludeDeletedFromIndex.Designer.cs
LeaderboardBackend/Migrations/20240831195900_LeaderboardsExcludeDeletedFromIndex.cs
LeaderboardBackend/Models/Entities/ApplicationContext.cs
LeaderboardBackend/Models/Entities/Category.cs
LeaderboardBackend/Models/Entities/Leaderboard.cs
LeaderboardBackend/Models/Entities/User.cs
LeaderboardBackend/Models/Validation/UsernameRule.cs

- updated EF tool and packages
- switched from non-deterministic collation to `citext`
- added missing check constraints
- filtered deleted LBs from slug index
Closes #235

DB Model Updates

---

LeaderboardBackend.Test/Features/Users/LoginTests.cs
LeaderboardBackend.Test/Features/Users/UserPasswordRuleTests.cs
LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend/Controllers/AccountController.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Filters/ValidationFilter.cs
LeaderboardBackend/Models/Requests/LeaderboardRequests.cs
LeaderboardBackend/Models/Requests/UserRequests.cs
LeaderboardBackend/Models/Validation/SlugRule.cs
LeaderboardBackend/Models/Validation/UserPasswordRule.cs
LeaderboardBackend/Models/Validation/UsernameRule.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/Results.cs
LeaderboardBackend/Services/ILeaderboardService.cs
LeaderboardBackend/Services/Impl/LeaderboardService.cs
LeaderboardBackend/openapi.json

Updates LB creation endpoint to be in line with the spec. Closes #223.
Also changes up some code around request object validation to handle more cases and just do stuff a little more elegantly.

Create LB Endpoint

---

LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Models/ViewModels/ConflictDetails.cs
LeaderboardBackend/Results.cs
LeaderboardBackend/Services/Impl/LeaderboardService.cs
LeaderboardBackend/openapi.json

Closes #270 and fixes the restore LB endpoint too.

Return Conflicting LB

---

LeaderboardBackend/Models/ViewModels/LeaderboardViewModel.cs
LeaderboardBackend/openapi.json

Remove Categories from LB View Model

---

LeaderboardBackend/Controllers/CategoriesController.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs

Closes: #278 
Depends on: #276

Add from route attr

---

LeaderboardBackend.Test/Categories.cs
LeaderboardBackend/Controllers/CategoriesController.cs
LeaderboardBackend/Models/ViewModels/CategoryViewModel.cs
LeaderboardBackend/openapi.json

Get Category Endpoint

---

LeaderboardBackend.Test/Categories.cs
LeaderboardBackend/Controllers/CategoriesController.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Services/ICategoryService.cs
LeaderboardBackend/Services/Impl/CategoryService.cs
LeaderboardBackend/openapi.json

Get Category by Slug Endpoint

---

LeaderboardBackend.Test/Categories.cs
LeaderboardBackend/Controllers/CategoriesController.cs
LeaderboardBackend/Services/ICategoryService.cs
LeaderboardBackend/Services/Impl/CategoryService.cs
LeaderboardBackend/openapi.json

Get Categories for Leaderboard Endpoint

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/openapi.json

Get Run Endpoint

---

LeaderboardBackend.Test/Lib/TestInitCommonFields.cs
LeaderboardBackend/Binders/UrlSafeBase64GuidBinder.cs
LeaderboardBackend/Controllers/UsersController.cs
LeaderboardBackend/Converters/GuidJsonConverter.cs
LeaderboardBackend/Program.cs

Closes #298 
Also:
* Updates the code style in `UrlSafeBase64GuidBinder`
* Removes the type guard in `GetUserById`'s route attribute that actually prevents the endpoint from being hit at all

Create Custom JsonConverter for Encoding GUIDs

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend.Test/TestApi/TestApiClient.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Filters/PaginatedAttribute.cs
LeaderboardBackend/Services/IRunService.cs
LeaderboardBackend/Services/Impl/RunService.cs
LeaderboardBackend/openapi.json

List Runs for Category

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Models/Requests/RunRequests.cs
LeaderboardBackend/Results.cs
LeaderboardBackend/Services/IRunService.cs
LeaderboardBackend/Services/Impl/RunService.cs
LeaderboardBackend/openapi.json

Update Runs Endpoint

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Services/IRunService.cs
LeaderboardBackend/Services/Impl/RunService.cs
LeaderboardBackend/openapi.json

Delete Run Endpoint

---

LeaderboardBackend/Controllers/CategoriesController.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Controllers/RunsController.cs

Closes: #313 
Replaces all action responses that call `ProblemDetailsFactory` with the `Problem()` helper function, except for those that add onto the `ProblemDetails` object.

Use Problem() in Controller Actions

---

LeaderboardBackend.Test/Runs.cs

In tests that update the user role, this PR calls `.Update()` instead of `.FindAsync()` to retrieve the user created for that test, to reduce a transaction call. This PR also actually updates the user role in some tests that don't update the role at all, when they're supposed to.

Call Update() to Update User Roles in Run Tests

---

LeaderboardBackend.Test/Leaderboards.cs

In tests that create users to test against their user roles, this PR reduces a transaction call on fetching said users.

Call Update() to Update User Role in Leaderboard Tests

---

LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Migrations/20250514212432_LeaderboardsAddSearchIndex.Designer.cs
LeaderboardBackend/Migrations/20250514212432_LeaderboardsAddSearchIndex.cs
LeaderboardBackend/Migrations/20250515210151_LeaderboardUseTsVectorGeneratedColumn.Designer.cs
LeaderboardBackend/Migrations/20250515210151_LeaderboardUseTsVectorGeneratedColumn.cs
LeaderboardBackend/Models/Entities/Leaderboard.cs
LeaderboardBackend/Services/ILeaderboardService.cs
LeaderboardBackend/Services/Impl/LeaderboardService.cs
LeaderboardBackend/openapi.json

Leaderboard Search Endpoint

---

LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend/Controllers/LeaderboardsController.cs
LeaderboardBackend/Models/Entities/Leaderboard.cs
LeaderboardBackend/Services/Impl/LeaderboardService.cs
LeaderboardBackend/openapi.json

Partially closes: #323 
~~Note: We may have to fundamentally change our search code. Current method doesn't allow fuzzy search, foundationally. Looking into [trigrams](https://www.npgsql.org/efcore/mapping/translations.html#trigram-functions), instead.~~ As discussed on Discord, we'll keep with this approach.

Ranking Leaderboard Search Results

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/ViewModels/RunViewModel.cs
LeaderboardBackend/Services/IRunService.cs
LeaderboardBackend/Services/Impl/RunService.cs
LeaderboardBackend/openapi.json

Get Records for Category Endpoint

---

LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/Controllers/RunsController.cs
LeaderboardBackend/Results.cs
LeaderboardBackend/Services/IRunService.cs
LeaderboardBackend/Services/Impl/RunService.cs

Restore Runs

---

.config/dotnet-tools.json
LeaderboardBackend.Test/Categories.cs
LeaderboardBackend.Test/Features/Users/ConfirmAccountTests.cs
LeaderboardBackend.Test/Features/Users/LoginTests.cs
LeaderboardBackend.Test/Features/Users/SendConfirmationTests.cs
LeaderboardBackend.Test/Features/Users/SendRecoveryTests.cs
LeaderboardBackend.Test/Features/Users/TestRecoveryTests.cs
LeaderboardBackend.Test/Fixtures/IntegrationTestsBase.cs
LeaderboardBackend.Test/Fixtures/PostgresDatabaseFixture.cs
LeaderboardBackend.Test/Leaderboards.cs
LeaderboardBackend.Test/Runs.cs
LeaderboardBackend.Test/TestApi/TestApiFactory.cs
LeaderboardBackend/LeaderboardBackend.csproj
LeaderboardBackend/Migrations/20250629224333_LeaderboardsNoNumericSlugs.Designer.cs
LeaderboardBackend/Migrations/20250629224333_LeaderboardsNoNumericSlugs.cs
LeaderboardBackend/Models/Entities/ApplicationContext.cs
LeaderboardBackend/Program.cs

This PR upgrades Entity Framework and related dependencies to version 9 and also simplifies DB setup and testing operations. Closes #337

Upgrade to EF 9

---

LeaderboardBackend.Test/Features/Users/SendConfirmationTests.cs
LeaderboardBackend.Test/Runs.cs
LeaderboardBackend/LeaderboardBackend.csproj
LeaderboardBackend/Models/Entities/Run.cs
LeaderboardBackend/Models/ViewModels/RunViewModel.cs
LeaderboardBackend/Program.cs
LeaderboardBackend/Services/IRunService.cs
LeaderboardBackend/Services/Impl/RunService.cs
LeaderboardBackend/openapi.json
global.json

Adds a rank to runs returned from the get records for category endpoint. Closes #319.

Run Ranking
