- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/suggest-a-task.md
Closes #3 
This adds a `.github` folder containing the CODEOWNERS file and ISSUE_TEMPLATE data. The issue templates are copied from the previous repo.
> Add CODEOWNERS and ISSUE_TEMPLATE

- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/UserService.cs
Closes #15 
Why would a system designed to work with JWTs use a claim mapping that automatically renames things to xmlsoap claim names? Your guess is as good as mine.
> Clear claim mapping JwtSecurityTokenHandler

- README.md
This adds the fact we need to pass `--urls <url>` in, where `<url>` matches the value of `applicationUrl` in the project's `launchSettings.json`.
> Update Readme on Running App from CLI

- LeaderboardBackend.Integration/Categories.cs
- LeaderboardBackend.Test/Controllers/CategoriesControllerTest.cs
- LeaderboardBackend.Test/Services/CategoryServiceTests.cs
- LeaderboardBackend/Controllers/Annotations/Conventions.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Controllers/UsersController.cs
- LeaderboardBackend/Models/Annotations/PlayersMaxAttribute.cs
- LeaderboardBackend/Models/Entities/Category.cs
- LeaderboardBackend/Models/Requests/Categories/Create.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/CategoryService.cs
- LeaderboardBackend/Services/ICategoryService.cs
Closes: #33. Based from: #34 
This creates the controller (and service) for Categories, plus one interaction from the MVP:
- An API client can get a category's fields by ID.
Future CategoriesController PRs will be based off of this
> MVP: Create Category Controller

- LeaderboardBackend/Program.cs
This will be useful for CI because we can pass stuff into the command
that actually runs tests rather than needing to mess with a .env file in
the CI script.
> Don't overwrite existing env vars

- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend.Test/Lib/HttpHelpers.cs
- LeaderboardBackend.Test/Lib/HttpRequestInit.cs
- LeaderboardBackend.Test/Lib/TestApiFactory.cs
- LeaderboardBackend.Test/Lib/TestInitCommonFields.cs
- LeaderboardBackend.Test/Lib/UserHelpers.cs
- LeaderboardBackend.Test/Modships.cs
- LeaderboardBackend.Test/Users.cs
- LeaderboardBackend/Authorization/JwtSecurityTokenHandlerSingleton.cs
- LeaderboardBackend/Authorization/MiddlewareResultHandler.cs
- LeaderboardBackend/Authorization/Requirements/UserTypeRequirement.cs
- LeaderboardBackend/Authorization/TokenValidationParametersSingleton.cs
- LeaderboardBackend/Authorization/UserTypeAuthorizationHandler.cs
- LeaderboardBackend/Authorization/UserTypeRequirement.cs
- LeaderboardBackend/Authorization/UserTypes.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Controllers/ModshipsController.cs
- LeaderboardBackend/Controllers/UsersController.cs
- LeaderboardBackend/Models/Entities/Modship.cs
- LeaderboardBackend/Models/Entities/User.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/IModshipService.cs
- LeaderboardBackend/Services/Impl/ModshipService.cs
- LeaderboardBackend/Services/Impl/UserService.cs
- README.md
Closes: #52.
Implements authorisation in the app based on our three current user types: admins, mods, and users. All controller actions now default to requiring authenticated users unless explicitly given the `[AllowAnonymous]` attribute. Also, actions requiring specific authZ will have an `[Authorize(Policy = <UserType>)]` attribute. These are handled by the `UserTypeAuthorizationHandler` class.
Todo:
> Authorisation

- LeaderboardBackend/Controllers/BansController.cs
- LeaderboardBackend/Services/IBanService.cs
- LeaderboardBackend/Services/Impl/BanService.cs
Refactor of the GET Bans method into two separate routes, one for leaderboard ID and one for user ID. Dropped route for GET all bans.
> refactor: split up GET Bans into two separate routes.

- LeaderboardBackend.Test/Runs.cs
- LeaderboardBackend/Controllers/RunsController.cs
- LeaderboardBackend/Services/IParticipationService.cs
- LeaderboardBackend/Services/Impl/ParticipationService.cs
Closes #39 GET Participations for Run as API client with ID (long; pk)
> 39 participations

- LeaderboardBackend/Authorization/UserTypeAuthorizationHandler.cs
- LeaderboardBackend/Controllers/JudgementsController.cs
- LeaderboardBackend/Controllers/ParticipationsController.cs
- LeaderboardBackend/Controllers/UsersController.cs
- LeaderboardBackend/Services/IAuthService.cs
- LeaderboardBackend/Services/IParticipationService.cs
- LeaderboardBackend/Services/IUserService.cs
- LeaderboardBackend/Services/Impl/AuthService.cs
- LeaderboardBackend/Services/Impl/ParticipationService.cs
- LeaderboardBackend/Services/Impl/UserService.cs
Added `GetUserIdFromClaims` and `GetEmailFromClaims` to the AuthService,
and use those instead of a UserService method to get the user from
claims. This makes for a more sane pattern throughout controllers using
claim data, and reduces database calls.
> Added AuthService method to get jwt claims

- .github/workflows/test-backend.yml
- LeaderboardBackend.Test/TestApi/TestApiFactory.cs
- LeaderboardBackend/AppConfig.cs
- LeaderboardBackend/Authorization/Jwt.cs
- LeaderboardBackend/Authorization/JwtConfig.cs
- LeaderboardBackend/Authorization/UserTypeAuthorizationHandler.cs
- LeaderboardBackend/LeaderboardBackend.csproj
- LeaderboardBackend/Models/Entities/ApplicationContextConfig.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/Impl/AuthService.cs
- LeaderboardBackend/Services/Impl/BanService.cs
- LeaderboardBackend/appsettings.Development.json
- LeaderboardBackend/appsettings.Staging.json
- README.md
- docker-compose.yml
- example.env
Changes:
* Refactored configuration to use the Options pattern
* Added configuration for db migration (will be useful for the dev env deployment)
* Changed the dotenv nuget to add dotenv as a configuration provider (only in Development env)
Going forward all new configuration should be strongly typed and validated.
The main benefit of using the [Options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0) is configuration validation.
Note that here I've injected it as `IOptions<ConfigObject>` in services, but `ConfigObject` could also be directly injected by also adding it as a singleton:
```csharp
builder.Services.AddSingleton(services => services.GetRequiredService<IOptions<ConfigObject>>().Value);
```
Injecting as `IOptions<>` …
> Strongly typed configuration + validation

- .github/workflows/test-backend.yml
- LeaderboardBackend.Jobs/LeaderboardBackend.Jobs.csproj
- LeaderboardBackend.Test/Bans.cs
- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Fixtures/PostgresDatabaseFixture.cs
- LeaderboardBackend.Test/Fixtures/TestConfig.cs
- LeaderboardBackend.Test/Judgements.cs
- LeaderboardBackend.Test/LeaderboardBackend.Test.csproj
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend.Test/Modships.cs
- LeaderboardBackend.Test/Runs.cs
- LeaderboardBackend.Test/TestApi/TestApiFactory.cs
- LeaderboardBackend.Test/Users.cs
- LeaderboardBackend/LeaderboardBackend.csproj
- LeaderboardBackend/Program.cs
- README.md
- docker-compose.yml
- example.env
Integration tests against an in-memory db are not reliable: some SQL requests can work perfectly against the in-memory db and fail on the real database. This PR aims to make running the tests against a real database very simple (no more docker-compose).
- Changed the README to mention the Docker dependency and how to run in-memory tests
- Made tests run against a temporary Postgres Docker container via the [Testcontainers library](https://dotnet.testcontainers.org/)
- The container is created only once and automatically deleted at the end.
- The database is reset by dropping the db and recreating it from an already seeded template DB.
- Changed the setup of some test classes to run only once for faster execution time.
- Removed db-test from docker-compose because it is replaced by …
> Run integration tests against a Postgres container (Testcontainers)

- fly.toml
Changes the app name in fly.toml from "lgg-backend-dev" to "lbgg-backend-dev"
> Change app name

- .config/dotnet-tools.json
- .gitattributes
- .github/workflows/test-backend.yml
- .gitignore
- Dockerfile
- LeaderboardBackend/LeaderboardBackend.csproj
- LeaderboardBackend/openapi.json
- fly.toml
- swagger-gen.env
- Fix `LeaderboardBackend.csproj` indendation according to the .editorconfig rules (2 spaces)
- Add a build step (.csproj line 60) that generates the `openapi.json` file using `dotnet tool run swagger`.
Since it needs to run the application to generate the file, it needs a valid configuration. So I added a `swagger-gen.env` file to be used with the CLI tool.
- Ensure `openapi.json` is checked out with LF line endings via `.gitattributes`, because the tool always generates with LF.
- Add a CI check in case the `openapi.json` changes were not committed.
Look at the latest commit separately to see the actual changes I made. The PR diff says I changed everything in the csproj because I fixed the indentation in the first commit.
- **Have an always up-to-date `openapi.json` file inside the …
> Automatically generate OpenApi spec file + CI check

- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Fixtures/TestConfig.cs
- LeaderboardBackend.Test/GlobalUsings.cs
- LeaderboardBackend.Test/LeaderboardBackend.Test.csproj
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Models/Entities/Leaderboard.cs
- LeaderboardBackend/Models/Entities/Modship.cs
- LeaderboardBackend/Models/ViewModels/CategoryViewModel.cs
- LeaderboardBackend/Models/ViewModels/LeaderboardViewModel.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
- LeaderboardBackend/openapi.json
Closes #136
- Added view models for `Leaderboard` and `Category`
- Added a way to get a leaderboard by its slug `GET /api/leaderboards/{slug}`
- Refactored the leaderboard tests with Bogus and FluentAssertions
- Added Bearer auth to the OpenAPI spec (also adds it to Swagger UI)
I broke the current [ViewModel guideline](https://github.com/leaderboardsgg/leaderboard-backend/wiki/Style-Guide#viewmodels) to show what I think would be better (this wasn't possible before the project was upgraded to .NET 7):
- Each property should be `required`
- A ViewModel should have a static `MapFrom(TDomainEntity entity)` method.
The `required` keyword ensures every property has been mapped. It doesn't work inside the constructor though so it needs to be a method.
> Get leaderboard by slug + add Leaderboard and Category view models

- LeaderboardBackend/AppConfig.cs
- LeaderboardBackend/Models/ViewModels/LeaderboardViewModel.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/openapi.json
Prevents Swashbuckle from generating the OpenAPI doc with fields marked as nullable, when we didn't explicitly mark them as such in our code.
Produces, for example:
> Allow Non-nullable Reference Types in OpenAPI Doc

- LeaderboardBackend.Test/Fixtures/IntegrationTestsBase.cs
- LeaderboardBackend.Test/LeaderboardBackend.Test.csproj
- LeaderboardBackend.Test/TestApi/TestApiFactory.cs
Fixes an issue where the testcontainers database is sometimes not yet initialized in OneTimeSetup methods of `IntegrationTestsBase` children. (noticed this issue with #169)
Also upgraded the testcontainers package since a new version has bugfixes for Docker detection. (@zysim had trouble with this)
> tests: ensure database initialization before OneTimeSetup of IntegrationTestsBase children runs

- LeaderboardBackend/Program.cs
Allows the doc to be viewable in the Fly.dev page, as it uses our Prd env.
Bear in mind; `UseSwaggerUI()` enables ASP.NET's [static file middleware](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/static-files?view=aspnetcore-7.0), as detailed in [this chapter in the Swashbuckle page](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-7.0&tabs=visual-studio-code#add-and-configure-swagger-middleware). Shouldn't be a problem, but just bear in mind to never put sensitive data in `wwwroot`, if we even create one in our project in the first place.
> Enable Swagger Doc to Be Accesible on Production

- LeaderboardBackend.Test/Features/Users/ConfirmAccountTests.cs
- LeaderboardBackend.Test/Features/Users/SendRecoveryTests.cs
- LeaderboardBackend.Test/Features/Users/TestRecoveryTests.cs
- LeaderboardBackend/Services/Impl/AccountRecoveryService.cs
> Replace AddAsync calls with Add calls

- LeaderboardBackend/Controllers/AccountController.cs
- LeaderboardBackend/Features.cs
- LeaderboardBackend/appsettings.json
Adds a feature flag for all account recovery features. Closes #200
> Account Recovery Feature Flag

- LeaderboardBackend/Controllers/UsersController.cs
- LeaderboardBackend/openapi.json
This PR cleans up GET /users/me so that the response codes actually make sense.
> Update GET /users/me

- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend/Authorization/MiddlewareResultHandler.cs
- LeaderboardBackend/Authorization/UserTypeAuthorizationHandler.cs
- LeaderboardBackend/Controllers/AccountController.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Controllers/RunsController.cs
- LeaderboardBackend/Controllers/UsersController.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/openapi.json
This PR makes endpoints that were erroneously requiring authorization work properly.
> Fix Anon Endpoints

- LeaderboardBackend.Test/Features/Emails/EmailSenderTests.cs
- LeaderboardBackend.Test/TestApi/TestApiFactory.cs
- LeaderboardBackend/LeaderboardBackend.csproj
- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/Impl/BrevoOptions.cs
- LeaderboardBackend/Services/Impl/BrevoService.cs
- LeaderboardBackend/Services/Impl/EmailSender.cs
- LeaderboardBackend/appsettings.json
- example.env
This PR deprecates the `EmailSender` service and replaces it with `BrevoService` which uses Brevo's REST API to send emails instead of an SMTP relay. Closes #208.
> Use Brevo Rest API

- .gitignore
- docker-compose.yml
Under the current docker compose setup - no database changes are saved if a container gets shut down. 
Adding a volume lets the database persist between compose runs when you choose not to use the daemon.
This also adds a .devcontainer gitignore for codespace configuration.
> Adds DB volume to docker compose db

- LeaderboardBackend/Controllers/AccountController.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Controllers/RunsController.cs
- LeaderboardBackend/Controllers/UsersController.cs
- LeaderboardBackend/LeaderboardBackend.csproj
- LeaderboardBackend/openapi.json
This PR simply adds operation IDs to all our endpoints. This stops API clients from autogenerating funny names for them that don't make any sense.
> Add Endpoint Operation IDs

- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend.Test/Runs.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
> Get Leaderboard Endpoint

- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Features/Users/ConfirmAccountTests.cs
- LeaderboardBackend.Test/Features/Users/RegistrationTests.cs
- LeaderboardBackend.Test/Features/Users/ResetPasswordTests.cs
- LeaderboardBackend.Test/Features/Users/TestRecoveryTests.cs
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Models/Entities/AccountConfirmation.cs
- LeaderboardBackend/Models/Entities/AccountRecovery.cs
- LeaderboardBackend/Models/Entities/ApplicationContext.cs
- LeaderboardBackend/Models/Entities/Category.cs
- LeaderboardBackend/Models/Entities/IHasCreationTimestamp.cs
- LeaderboardBackend/Models/Entities/IHasUpdateTimestamp.cs
- LeaderboardBackend/Models/Entities/Leaderboard.cs
- LeaderboardBackend/Models/Entities/Run.cs
- LeaderboardBackend/Models/Entities/User.cs
- LeaderboardBackend/Services/Impl/AccountConfirmationService.cs
- LeaderboardBackend/Services/Impl/AccountRecoveryService.cs
- LeaderboardBackend/Services/Impl/UserService.cs
What it says on the tin. Had to mess with the tests a bit to get this working properly. Also removes erroneously overridden `Equals` and `GetHashCode` on models (this is a no-no). Closes #237
> Automatically Set CreatedAt and UpdatedAt

- LeaderboardBackend.Test/Leaderboards.cs
This PR simply adds a test to make sure that deleted boards aren't hogging slugs.
> Add Test for Filtered Index

- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Models/ViewModels/LeaderboardViewModel.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
- LeaderboardBackend/openapi.json
This PR essentially splits the get leaderboards endpoint into two. If you provide IDs, it'll return only the Leaderboards with those IDs; otherwise, it'll return all non-deleted Leaderboards. Closes #227
> List Leaderboards Endpoint

- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
- LeaderboardBackend/openapi.json
> includeDeleted Param

- LeaderboardBackend/Program.cs
This PR makes it so that enums on DTOs will not accept integer values when deserializing from JSON. Closes #267
> Disable int Parsing for Enums

- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Results.cs
- LeaderboardBackend/Services/ICategoryService.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/Impl/CategoryService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
- LeaderboardBackend/openapi.json
Closes: #265 
Dependent on #274
> Restore Categories

- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend.Test/Runs.cs
- LeaderboardBackend/Extensions/GuidExtensions.cs
- LeaderboardBackend/Migrations/20250227064305_Runs_SetInfoNonNullable.Designer.cs
- LeaderboardBackend/Migrations/20250227064305_Runs_SetInfoNonNullable.cs
- LeaderboardBackend/Models/Entities/Run.cs
- LeaderboardBackend/Models/Requests/RunRequests.cs
- LeaderboardBackend/Models/ViewModels/RunViewModel.cs
- LeaderboardBackend/Services/Impl/RunService.cs
- LeaderboardBackend/openapi.json
> Run Data Changes

- LeaderboardBackend.Test/Categories.cs
In tests that set the user role, this PR saves a transaction call by replacing `FindAsync` calls with `Update` calls. This PR also fills in tests that don't actually update the user role when they're supposed to.
> Call Update() to Update User Roles in Category Tests

- .config/dotnet-tools.json
- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend.Test/Runs.cs
- LeaderboardBackend/Controllers/CategoriesController.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Controllers/RunsController.cs
- LeaderboardBackend/LeaderboardBackend.csproj
- LeaderboardBackend/Models/Entities/Category.cs
- LeaderboardBackend/Models/Entities/IHasDeletionTimestamp.cs
- LeaderboardBackend/Models/Entities/Leaderboard.cs
- LeaderboardBackend/Models/Entities/Run.cs
- LeaderboardBackend/Models/Requests/StatusFilter.cs
- LeaderboardBackend/Models/Status.cs
- LeaderboardBackend/Models/ViewModels/CategoryViewModel.cs
- LeaderboardBackend/Models/ViewModels/LeaderboardViewModel.cs
- LeaderboardBackend/Models/ViewModels/RunViewModel.cs
- LeaderboardBackend/Program.cs
- LeaderboardBackend/Services/ICategoryService.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/IRunService.cs
- LeaderboardBackend/Services/Impl/CategoryService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
- LeaderboardBackend/Services/Impl/RunService.cs
- LeaderboardBackend/openapi.json
This PR adds a new Status field to all resources that can be deleted and changes any endpoints that return a list of these resources to take a status filter param instead of `includeDeleted`. Swagger settings are also updated so that enum values will have their defaults recorded in the spec if present. Closes #309.
> Add Statuses

- LeaderboardBackend.Test/Features/Users/LoginTests.cs
- LeaderboardBackend/Controllers/AccountController.cs
- LeaderboardBackend/Services/IUserService.cs
- LeaderboardBackend/Services/Impl/UserService.cs
- LeaderboardBackend/openapi.json
Closes: #176 
* 404 error becomes 401 (if a user isn't found in the DB, it 401s, same as bad credentials)
* 403 error check only triggers after checking password is correct, when it triggered before
Todos:
> Reduce Login Error Specificity

- LeaderboardBackend.Test/Categories.cs
- LeaderboardBackend.Test/Leaderboards.cs
- LeaderboardBackend/Controllers/LeaderboardsController.cs
- LeaderboardBackend/Models/Entities/Category.cs
- LeaderboardBackend/Models/Entities/Leaderboard.cs
- LeaderboardBackend/Models/Entities/Run.cs
- LeaderboardBackend/Models/ICounts.cs
- LeaderboardBackend/Models/ViewModels/LeaderboardViewModel.cs
- LeaderboardBackend/Results.cs
- LeaderboardBackend/Services/ILeaderboardService.cs
- LeaderboardBackend/Services/Impl/LeaderboardService.cs
- LeaderboardBackend/Services/Impl/RunService.cs
- LeaderboardBackend/openapi.json
This PR makes it so that querying a leaderboard also returns a number indicating how many runs are on that board total. Deleted runs and runs belonging to deleted cats are not counted.
> Add Leaderboard Stats
